# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27dfea64cf4a396f4b9d9e7aa559a1216fd38ba40e3d91720f012a979ebba12a503862484aa2d9f301fe867d1541c8bac30328797ae7ac2e9c4c9bd764a9893e

test:
  secret_key_base: ae680228d236cde789f48830efc302048f3693bb122eb9802b5c5be82e04263589bd8d6087bd8857bc42fbf09be600cb910c41b9e1b6b0b37391f197f0d254b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
